from __future__ import annotations

from zoneinfo import ZoneInfo

from digital_twin.domain.weather import (
    DEFAULT_LOCAL_TIMEZONE,
    DEFAULT_WEATHER_LOCATION_NAME,
)

LOCATION_NAME = DEFAULT_WEATHER_LOCATION_NAME
LOCAL_TZ = ZoneInfo(DEFAULT_LOCAL_TIMEZONE)
ANFIS_DECISION_THRESHOLD = 0.72
ANFIS_FORECAST_DECISION_THRESHOLD = 0.78
HOURLY_CHART_MAX_RANGE_DAYS = 7
