from __future__ import annotations

from digital_twin.domain.weather import DEFAULT_WEATHER_LOCATION

LOCATION_NAME = DEFAULT_WEATHER_LOCATION.name
LOCAL_TZ = DEFAULT_WEATHER_LOCATION.timezone_info()
ANFIS_DECISION_THRESHOLD = 0.72
ANFIS_FORECAST_DECISION_THRESHOLD = 0.78
HOURLY_CHART_MAX_RANGE_DAYS = 7
