from __future__ import annotations

IRRIGATION_SLOT_MORNING = "morning"
IRRIGATION_SLOT_EVENING = "evening"
IRRIGATION_SLOT_WINTER_CHECK = "winter_check"
IRRIGATION_SLOT_DAILY_PRESCRIPTION = "daily_prescription"

IRRIGATION_SLOTS = (
    IRRIGATION_SLOT_MORNING,
    IRRIGATION_SLOT_EVENING,
    IRRIGATION_SLOT_WINTER_CHECK,
    IRRIGATION_SLOT_DAILY_PRESCRIPTION,
)

IRRIGATION_STATUS_PLANNED = "planned"
IRRIGATION_STATUS_RUNNING = "running"
IRRIGATION_STATUS_COMPLETED = "completed"
IRRIGATION_STATUS_SKIPPED = "skipped"
IRRIGATION_STATUS_CANCELLED = "cancelled"
IRRIGATION_STATUS_FAILED = "failed"

IRRIGATION_EVENT_STATUSES = (
    IRRIGATION_STATUS_PLANNED,
    IRRIGATION_STATUS_RUNNING,
    IRRIGATION_STATUS_COMPLETED,
    IRRIGATION_STATUS_SKIPPED,
    IRRIGATION_STATUS_CANCELLED,
)
IRRIGATION_ACTUATION_STATUSES = (
    IRRIGATION_STATUS_PLANNED,
    IRRIGATION_STATUS_RUNNING,
    IRRIGATION_STATUS_COMPLETED,
    IRRIGATION_STATUS_SKIPPED,
    IRRIGATION_STATUS_CANCELLED,
    IRRIGATION_STATUS_FAILED,
)

IRRIGATION_ACTUATOR_NODE = "irrigation-actuator"

__all__ = [
    "IRRIGATION_ACTUATION_STATUSES",
    "IRRIGATION_ACTUATOR_NODE",
    "IRRIGATION_EVENT_STATUSES",
    "IRRIGATION_SLOT_DAILY_PRESCRIPTION",
    "IRRIGATION_SLOT_EVENING",
    "IRRIGATION_SLOT_MORNING",
    "IRRIGATION_SLOT_WINTER_CHECK",
    "IRRIGATION_SLOTS",
    "IRRIGATION_STATUS_CANCELLED",
    "IRRIGATION_STATUS_COMPLETED",
    "IRRIGATION_STATUS_FAILED",
    "IRRIGATION_STATUS_PLANNED",
    "IRRIGATION_STATUS_RUNNING",
    "IRRIGATION_STATUS_SKIPPED",
]
