from __future__ import annotations

WATER_NEED_LOW = "low"
WATER_NEED_MEDIUM = "medium"
WATER_NEED_HIGH = "high"
WATER_NEED_LEVELS = (WATER_NEED_LOW, WATER_NEED_MEDIUM, WATER_NEED_HIGH)

PLANT_TYPE_VEGETABLES = "vegetables"
PLANT_TYPE_HERBS = "herbs"
PLANT_TYPE_ORNAMENTALS = "ornamentals"
PLANT_TYPE_SUCCULENTS = "succulents"
PLANT_TYPE_CODES = (
    PLANT_TYPE_VEGETABLES,
    PLANT_TYPE_HERBS,
    PLANT_TYPE_ORNAMENTALS,
    PLANT_TYPE_SUCCULENTS,
)

PLANT_TYPE_LABELS = {
    PLANT_TYPE_VEGETABLES: "Vegetables",
    PLANT_TYPE_HERBS: "Herbs",
    PLANT_TYPE_ORNAMENTALS: "Ornamentals",
    PLANT_TYPE_SUCCULENTS: "Succulents",
}

__all__ = [
    "PLANT_TYPE_CODES",
    "PLANT_TYPE_HERBS",
    "PLANT_TYPE_LABELS",
    "PLANT_TYPE_ORNAMENTALS",
    "PLANT_TYPE_SUCCULENTS",
    "PLANT_TYPE_VEGETABLES",
    "WATER_NEED_HIGH",
    "WATER_NEED_LEVELS",
    "WATER_NEED_LOW",
    "WATER_NEED_MEDIUM",
]
