from __future__ import annotations

POT_SIZE_HUGE = "huge"
POT_SIZE_LARGE = "large"
POT_SIZE_MEDIUM = "medium"
POT_SIZE_SMALL = "small"
POT_SIZE_CLASSES = (POT_SIZE_HUGE, POT_SIZE_LARGE, POT_SIZE_MEDIUM, POT_SIZE_SMALL)

SMALL_POT_7CM = "7cm"
SMALL_POT_15CM = "15cm"
SMALL_POT_30CM = "30cm"
SMALL_POT_SUBTYPES = (SMALL_POT_7CM, SMALL_POT_15CM, SMALL_POT_30CM)

RAIN_EXPOSURE_COVERED = "covered"
RAIN_EXPOSURE_PARTIALLY_EXPOSED = "partially_exposed"
RAIN_EXPOSURE_FULLY_EXPOSED = "fully_exposed"
RAIN_EXPOSURES = (
    RAIN_EXPOSURE_COVERED,
    RAIN_EXPOSURE_PARTIALLY_EXPOSED,
    RAIN_EXPOSURE_FULLY_EXPOSED,
)

SUN_EXPOSURE_SHADE = "shade"
SUN_EXPOSURE_PARTIAL = "partial"
SUN_EXPOSURE_FULL = "full"
SUN_EXPOSURE_REFLECTED_HEAT = "reflected_heat"
SUN_EXPOSURES = (
    SUN_EXPOSURE_SHADE,
    SUN_EXPOSURE_PARTIAL,
    SUN_EXPOSURE_FULL,
    SUN_EXPOSURE_REFLECTED_HEAT,
)

WIND_EXPOSURE_SHELTERED = "sheltered"
WIND_EXPOSURE_MODERATE = "moderate"
WIND_EXPOSURE_GUSTY = "gusty"
WIND_EXPOSURES = (
    WIND_EXPOSURE_SHELTERED,
    WIND_EXPOSURE_MODERATE,
    WIND_EXPOSURE_GUSTY,
)

__all__ = [
    "POT_SIZE_CLASSES",
    "POT_SIZE_HUGE",
    "POT_SIZE_LARGE",
    "POT_SIZE_MEDIUM",
    "POT_SIZE_SMALL",
    "RAIN_EXPOSURES",
    "RAIN_EXPOSURE_COVERED",
    "RAIN_EXPOSURE_FULLY_EXPOSED",
    "RAIN_EXPOSURE_PARTIALLY_EXPOSED",
    "SMALL_POT_15CM",
    "SMALL_POT_30CM",
    "SMALL_POT_7CM",
    "SMALL_POT_SUBTYPES",
    "SUN_EXPOSURES",
    "SUN_EXPOSURE_FULL",
    "SUN_EXPOSURE_PARTIAL",
    "SUN_EXPOSURE_REFLECTED_HEAT",
    "SUN_EXPOSURE_SHADE",
    "WIND_EXPOSURES",
    "WIND_EXPOSURE_GUSTY",
    "WIND_EXPOSURE_MODERATE",
    "WIND_EXPOSURE_SHELTERED",
]
