from __future__ import annotations

DEFAULT_SENSOR_SOURCE = "simulated_sensor"
ACTUAL_SENSOR_SOURCE = "actual_sensor"
ACTUATOR_FEEDBACK_SOURCE = "actuator_feedback"
SPARSE_FORECAST_SENSOR_SOURCE = "forecast_simulated_sensor"

SENSOR_SOURCES = (
    DEFAULT_SENSOR_SOURCE,
    ACTUAL_SENSOR_SOURCE,
    ACTUATOR_FEEDBACK_SOURCE,
    SPARSE_FORECAST_SENSOR_SOURCE,
)

RAW_RESOLUTION = "raw_15min"
HOURLY_RESOLUTION = "hourly"
DAILY_RESOLUTION = "daily"
SENSOR_READING_RESOLUTIONS = (RAW_RESOLUTION, HOURLY_RESOLUTION, DAILY_RESOLUTION)

ACTUAL_READING_INTERVAL_MINUTES = 15

__all__ = [
    "ACTUAL_READING_INTERVAL_MINUTES",
    "ACTUAL_SENSOR_SOURCE",
    "ACTUATOR_FEEDBACK_SOURCE",
    "DAILY_RESOLUTION",
    "DEFAULT_SENSOR_SOURCE",
    "HOURLY_RESOLUTION",
    "RAW_RESOLUTION",
    "SENSOR_READING_RESOLUTIONS",
    "SENSOR_SOURCES",
    "SPARSE_FORECAST_SENSOR_SOURCE",
]
