from __future__ import annotations

DEFAULT_WEATHER_LOCATION_NAME = "Cluj-Napoca"
DEFAULT_WEATHER_LATITUDE = 46.7712
DEFAULT_WEATHER_LONGITUDE = 23.6236
DEFAULT_LOCAL_TIMEZONE = "Europe/Bucharest"

DEFAULT_WEATHER_LOCATION = {
    "location_name": DEFAULT_WEATHER_LOCATION_NAME,
    "latitude": DEFAULT_WEATHER_LATITUDE,
    "longitude": DEFAULT_WEATHER_LONGITUDE,
    "timezone": DEFAULT_LOCAL_TIMEZONE,
}

OPEN_METEO_ARCHIVE_SOURCE = "open-meteo-archive"
OPEN_METEO_FORECAST_SOURCE = "open-meteo-forecast"
ESTIMATED_WEATHER_SOURCE = "estimated-weather"

WEATHER_REFRESH_STATUS_RUNNING = "running"
WEATHER_REFRESH_STATUS_COMPLETED = "completed"
WEATHER_REFRESH_STATUS_FAILED = "failed"
WEATHER_REFRESH_STATUSES = (
    WEATHER_REFRESH_STATUS_RUNNING,
    WEATHER_REFRESH_STATUS_COMPLETED,
    WEATHER_REFRESH_STATUS_FAILED,
)

__all__ = [
    "DEFAULT_LOCAL_TIMEZONE",
    "DEFAULT_WEATHER_LATITUDE",
    "DEFAULT_WEATHER_LOCATION",
    "DEFAULT_WEATHER_LOCATION_NAME",
    "DEFAULT_WEATHER_LONGITUDE",
    "ESTIMATED_WEATHER_SOURCE",
    "OPEN_METEO_ARCHIVE_SOURCE",
    "OPEN_METEO_FORECAST_SOURCE",
    "WEATHER_REFRESH_STATUSES",
    "WEATHER_REFRESH_STATUS_COMPLETED",
    "WEATHER_REFRESH_STATUS_FAILED",
    "WEATHER_REFRESH_STATUS_RUNNING",
]
